name: CI

on: [push, pull_request]

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                config:
                    # Use 2016 image as 2019 does not have VC++ 14.0 compiler.
                    # https://github.community/t5/GitHub-Actions/Microsoft-Visual-C-14-0-compiler-not-available-on-Windows-2019/m-p/32871
                    - os-image: windows-2016
                      os-name: windows
                      python-version: '3.9'
                      python-arch: '64'
                      numpy-version: '1.19'

        runs-on: ${{ matrix.config.os-image }}

        steps:
            - uses: actions/checkout@v1
              with:
                  submodules: true

            - name: Build wheels (Windows)
              if: matrix.config.os-name == 'windows'
              run: .github/scripts/build-windows.ps1
              shell: pwsh
              env:
                  PYTHON_VERSION: ${{ matrix.config.python-version }}
                  PYTHON_ARCH: ${{ matrix.config.python-arch }}
                  NUMPY_VERSION: ${{ matrix.config.numpy-version }}

            - name: Store wheels as artifacts
              uses: actions/upload-artifact@v1
              with:
                  name: wheels
                  path: dist
